FROM scratch

LABEL org.opencontainers.image.title="blockasaurus" \
  org.opencontainers.image.vendor="chrissnell" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.description="Fast and lightweight DNS proxy as ad-blocker for local network"

USER 100
WORKDIR /app

COPY blockasaurus /app/blockasaurus

ENV BLOCKY_CONFIG_FILE=/app/config.yml

ENTRYPOINT ["/app/blockasaurus"]

HEALTHCHECK --start-period=1m --timeout=3s CMD ["/app/blockasaurus", "healthcheck"]
