{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "blockasaurus.fullname" . }}
  labels:
    {{- include "blockasaurus.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName | default (printf "%s-tls" (include "blockasaurus.fullname" .)) }}
  {{- with .Values.certificate.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.certificate.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  {{- with .Values.certificate.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.commonName }}
  commonName: {{ . | quote }}
  {{- end }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind | default "ClusterIssuer" }}
  {{- with .Values.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
