{{- if and .Values.service.adminPort.enabled .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blockasaurus.fullname" . }}-admin
  labels:
    {{- include "blockasaurus.labels" . | nindent 4 }}
  {{- with .Values.ingress.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.admin.className }}
  ingressClassName: {{ .Values.ingress.admin.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.admin.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "blockasaurus.fullname" $ }}-admin
                port:
                  name: admin
          {{- end }}
    {{- end }}
{{- end }}
