{{- if .Values.service.splitUIPort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockasaurus.fullname" . }}-split-ui
  labels:
    {{- include "blockasaurus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.splitUIPort.type }}
  ports:
    - name: split-ui
      port: {{ .Values.service.splitUIPort.port }}
      targetPort: split-ui
      protocol: TCP
  selector:
    {{- include "blockasaurus.selectorLabels" . | nindent 4 }}
{{- end }}
